### ISSUE TITLE
"Application error" on https://wp-current-events-rss.herokuapp.com/

### ISSUE THREAD

**Issue by Myer** [clokep/wp-current-events-rss#4]
I'm getting an "Application Error" on https://wp-current-events-rss.herokuapp.com/.
My RSS-reader (Inoreader) also reports it couldn't fetch the feed since 25.06.2017 13:19 UTC+2. The crawl at 11:18 same day still worked.

**Comment by clokep** [comment]
I ran out of hours on my free Heroku instance! Working on moving this to another host. Probably won't happen until next week though (holiday here in the US). Sorry for the inconvenience!

**Comment by clokep** [comment]
So this is back up due to it being July, but I suspect it'll only last a few weeks again. Have some ideas of where else to host this that will be more robust.

This was down for other reasons the past few days though (see #5).

**Comment by clokep** [comment]
Just wanted to comment on here that I changed hosts and this shouldn't happen anymore...but you'll need to update your RSS feed reader to point to https://www.to-rss.xyz/wikipedia/current_events/
